### 1. async 函数
#### 函数的返回值为promise对象
#### promise对象的结果由async函数的返回值决定
async函数返回的结果处理，和then方法相同。
* async函数返回一个非promise对象
```javascript
async function main() {
    // return 123;
    return undefined
}
let result = main();
/**
 * PromiseStatus: 'fullfilled',
 * PromiseResult: undefined 
 * **/
```

* async函数返回一个promise对象
```javascript
async function main() {
    return new Promise((resolve, reject) => {
        resolve('ok')
    });
}
let result = main();
/**
 * PromiseStatus: 'fullfilled',
 * PromiseResult: 'ok' 
 * **/
```
```javascript
async function main() {
    return new Promise((resolve, reject) => {
        reject('Error')
    });
}
let result = main();
/**
 * PromiseStatus: 'rejected',
 * PromiseResult: 'Error' 
 * **/
```

* 抛出异常
```javascript
async function main() {
    throw 'oh no'
}
let result = main();
/**
 * PromiseStatus: 'rejected',
 * PromiseResult: 'oh no' 
 * **/
```

### 2. await
#### 只能在async函数中使用
#### await的返回值
* 如果await右侧为promise对象，则返回结果为promise的成功的值
```javascript
let p = Promise.resolve('ok');
async function main() {
    let result = await p;
    console.log(result); // 'ok'
}
```
* 如果await右侧为promise对象， promise失败，使用try,catch处理
```javascript
let p = Promise.reject('Error');
async function main() {
    try{
        let result = await p;
    }catch(e){
        console.log(e); // 'Error'
    }
}
```
* 如果await右侧不是promise对象，则返回结果为右侧值
```javascript
async function main() {
    let result = await 123;
    console.log(result); // 123
}
```